//
//  DataRecipe.swift
//  MyFirstProject
//
//  Created by Vincenzo De Simone on 29/05/23.
//

import SwiftUI

class RecipeData: ObservableObject {
        
    @Published var recipes = [
    
    Recipe(name: "Carrot and Sage Fritters", ingredients: ["Carrots", "Sage"], quantity: [4, 250], preparation_time: "15 mins", type_dish: "First course", nutritional_values: "450 kcal", conservation: "Fridge", imageName: "frittelle", description: "Peel the carrots, trim them and then grate them into julienne strips. Leave them in a cotton tea towel to dry and in the meantime prepare the batter. Shell the eggs in a bowl, beat them after having seasoned them with salt and pepper.\n\nAdd the flour, a spoonful at a time, and work with an electric mixer to obtain a homogeneous batter. Let the batter rest and in the meantime sauté the sausage in a very hot non-stick pan. When the sausage is golden brown, remove it from the pan and let it dry and cool on kitchen paper.\n\nWhen the sausage is warm, pour it into the batter together with the carrots, mix well with a fork so that all the ingredients blend perfectly. Put plenty of frying oil in a deep frying pan and when it is hot, take a little carrots and batter with a spoon or ladle and put them to fry.\n\nAbout 10 minutes will be enough for a homogeneous cooking, 5 on each side. Remove the carrot and sausage fritters and let them dry on the paper towels.\n\nServe them still hot after a sprinkling of salt and using some sage leaves that you could also fry if you wish. Also bring some lemon wedges to the table.", isLiked: false),
    
    Recipe(name: "Carrot and Spinach Meatballs", ingredients: ["Carrots", "Spinach"], quantity: [4, 800], preparation_time: "15 mins", type_dish: "Second course", nutritional_values: "340 kcal", conservation: "Fridge", imageName: "polpette", description: "Peel and grate the carrots. Squeeze out any excess moisture using a clean kitchen towel. Blanch the spinach in boiling water for a few minutes until wilted. Drain and finely chop. In a mixing bowl, combine the grated carrots, chopped spinach, salt, pepper, bread crumbs, grated Parmesan cheese, minced garlic, and beaten egg. Mix well until all ingredients are evenly combined. \n\nShape the mixture into small meatballs, about the size of a golf ball. Place them on a baking sheet lined with parchment paper. Preheat the oven to 375°F (190°C). Heat olive oil in a large skillet over medium heat. Add the meatballs in batches and cook until browned on all sides, turning them gently with a spatula. This step helps to seal in the flavors and give the meatballs a nice crust. \n\nTransfer the browned meatballs to a baking dish and pour tomato sauce over them. Make sure the meatballs are coated in the sauce. Bake in the preheated oven for about 20-25 minutes or until the meatballs are cooked through and the sauce is bubbling. Serve the carrot and spinach meatballs hot with additional grated Parmesan cheese and your favorite pasta or crusty bread.", isLiked: true),
    
    Recipe(name: "Quinoa Salad", ingredients: ["Quinoa", "Cucumbers", "Cherry Tomatoes", "Olives", "Lemon"], quantity: [200, 1, 10, 10, 2, 1], preparation_time: "20 mins", type_dish: "Appetizer", nutritional_values: "350 kcal", conservation: "Fridge", imageName: "insalata_quinoa", description: "Rinse the quinoa under cold water to remove any bitterness. In a saucepan, combine the quinoa and water or vegetable broth. Bring to a boil, then reduce heat and simmer for about 15-20 minutes, or until the quinoa is tender and the liquid is absorbed. Remove the cooked quinoa from heat and let it cool. In a large bowl, combine the cooked quinoa, diced cucumber, cherry tomatoes, and sliced black olives. \n\nIn a small bowl, whisk together the lemon juice, olive oil, salt, and pepper. Pour the dressing over the quinoa salad and toss to coat. If desired, sprinkle with chopped fresh herbs for added freshness and flavor. Serve chilled or at room temperature.", isLiked: false),
    
    Recipe(name: "Chickpea Hummus", ingredients: ["Chickpeas", "Tahini", "Garlic", "Lemon"], quantity: [400, 4, 1, 2, 1], preparation_time: "10 mins", type_dish: "Appetizer", nutritional_values: "200 kcal", conservation: "Fridge", imageName: "hummus_ceci", description: "In a food processor, combine the chickpeas, tahini, minced garlic, lemon juice, and olive oil. Process until smooth and creamy. If the mixture is too thick, add a little water or more olive oil. Season with salt and any additional spices to taste. Transfer the hummus to a serving dish and drizzle with olive oil. Sprinkle with paprika or other spices for garnish, if desired. Serve with fresh vegetables, pita bread, or your favorite crackers.", isLiked: false),
    
    Recipe(name: "Lentil Soup", ingredients: ["Lentils", "Onion", "Carrots", "Celery", "Vegetable Broth", "Rosemary"], quantity: [250, 1, 2, 2, 500, 1], preparation_time: "40 mins", type_dish: "First course", nutritional_values: "300 kcal", conservation: "Fridge", imageName: "zuppa_lenticchie", description: "In a large pot, heat a drizzle of olive oil over medium heat. Add the diced onion, carrots, and celery. Sauté for about 5 minutes, or until the vegetables are softened. Add the minced garlic, ground cumin, ground coriander, and paprika to the pot. \n\nStir well to coat the vegetables in the spices and cook for an additional minute. Add the rinsed lentils, diced tomatoes (with their juice), and vegetable broth to the pot. Stir to combine. Bring the soup to a boil, then reduce the heat to low. Cover the pot and let it simmer for about 30-40 minutes, or until the lentils are tender. \n\nOnce the lentils are cooked, season the soup with salt and pepper to taste. Adjust the seasoning and thickness of the soup by adding more broth if desired. If desired, use an immersion blender to partially blend the soup to create a thicker consistency. \n\nAlternatively, remove about half of the soup and blend it in a blender or food processor, then return it to the pot. Serve the lentil soup hot, garnished with fresh herbs if desired. Enjoy your comforting and nutritious lentil soup!", isLiked: false),
    
    Recipe(name: "Vegetable Curry", ingredients: ["Cauliflower", "Potatoes", "Carrots", "Bell Peppers", "Onion", "Curry", "Coconut Milk"], quantity: [1, 2, 2, 2, 1, 2, 400], preparation_time: "50 mins", type_dish: "Second course", nutritional_values: "400 kcal", conservation: "Fridge", imageName: "curry_verdure", description: "Heat the vegetable oil in a large saucepan or skillet over medium heat. Add the diced onion and sauté for about 5 minutes, or until it becomes translucent. Add the minced garlic and grated ginger to the pan and cook for another 1-2 minutes, until fragrant. \n\nIn a small bowl, combine the curry powder, ground cumin, ground coriander, turmeric, paprika, and cayenne pepper (if using). Stir to create a spice mixture. Add the spice mixture to the pan with the onions, garlic, and ginger. Stir well to coat the onions and spices evenly. Pour in the diced tomatoes (with their juice) and coconut milk. Stir to combine all the ingredients. Add the diced mixed vegetables to the pan and stir to coat them with the sauce. Reduce the heat to low and cover the pan with a lid. \n\nLet the curry simmer for about 15-20 minutes, or until the vegetables are cooked to your desired tenderness. Taste the curry and add salt as needed. Remove the pan from heat and garnish the vegetable curry with freshly chopped cilantro. Serve the vegetable curry hot over cooked rice or with naan bread on the side.",  isLiked: false),
    
    Recipe(name: "Baked Tofu", ingredients: ["Tofu", "Soy Sauce", "Ginger"], quantity: [200, 4, 2, 1, 2], preparation_time: "30 mins", type_dish: "Second course", nutritional_values: "250 kcal", conservation: "Fridge", imageName: "tofu_forno", description: "In a large pot or skillet, heat the cooking oil over medium heat. Add the diced onion and minced garlic. Sauté for a few minutes until the onion becomes translucent and fragrant. Add the curry powder, ground cumin, ground coriander, turmeric powder, and cayenne pepper (if using). Stir well to coat the onions and garlic with the spices. Cook for an additional minute to toast the spices and enhance their flavors. \n\nAdd the diced potatoes, carrots, bell pepper, and cauliflower florets to the pot. Stir to combine and coat the vegetables with the spice mixture. Pour in the coconut milk and season with salt and pepper. Stir well to ensure the vegetables are evenly coated with the coconut milk and spices. Bring the mixture to a simmer, then reduce the heat to low. \n\nCover the pot and let the curry simmer for about 20-25 minutes, or until the vegetables are tender. Taste and adjust the seasoning as needed, adding more salt or spices if desired. Once the vegetables are cooked and the flavors have melded together, remove the pot from heat. Serve the vegetable curry hot over steamed rice or with naan bread. Garnish with fresh cilantro leaves for added freshness and flavor.", isLiked: false),
    
    Recipe(name: "Basil Pesto Pasta", ingredients: ["Basil", "Pine Nuts", "Garlic", "Salt"], quantity: [320, 50, 30, 2, 4, 1], preparation_time: "15 mins", type_dish: "First course", nutritional_values: "400 kcal", conservation: "Fridge", imageName: "pasta_pesto", description:"In a food processor or blender, combine the fresh basil leaves, grated Parmesan cheese, pine nuts or walnuts, and garlic cloves. Pulse a few times until the ingredients are roughly chopped and well combined. While the food processor is running, slowly drizzle in the extra-virgin olive oil until the mixture becomes smooth and creamy. Taste the pesto and season with salt and pepper according to your preference. \n\nAdjust the flavors as needed. Cook the pasta according to the package instructions until al dente. Drain the cooked pasta, reserving a small amount of the pasta water. In a large mixing bowl, combine the cooked pasta with the prepared basil pesto sauce. \n\nToss well to coat the pasta evenly. If the pesto pasta seems dry, add a splash of the reserved pasta water to loosen it up and create a smoother consistency. Serve the basil pesto pasta hot, garnished with some extra grated Parmesan cheese and fresh basil leaves if desired. Enjoy your delicious and vibrant basil pesto pasta!" , isLiked: false),
    
    Recipe(name: "Lentil Burger", ingredients: ["Lentils", "Onion", "Carrots", "Breadcrumbs", "Chickpea Flour", "Tomatoes", "Lettuce"], quantity: [250, 1, 2, 100, 50, 2, 4], preparation_time: "1h", type_dish: "Second course", nutritional_values: "350 kcal", conservation: "Fridge", imageName: "burger_lenticchie", description: "Rinse the lentils under cold water and cook them according to the package instructions until they are tender. Drain and set aside. In a large mixing bowl, mash the cooked lentils using a fork or potato masher until they are partially mashed but still have some texture. Add the finely chopped onion, minced garlic, grated carrot, breadcrumbs, flour, tomato paste, ground cumin, paprika, salt, and pepper to the bowl with the lentils. Mix all the ingredients together until well combined. If the mixture feels too wet, you can add more breadcrumbs or flour to help bind it. \n\nShape the lentil mixture into burger patties of your desired size. The mixture should hold together well, but if it's too sticky, you can wet your hands with water or lightly coat them with oil to prevent sticking. Heat a drizzle of cooking oil in a large skillet over medium heat. Once the oil is hot, add the lentil burgers to the skillet. \n\nCook them for about 4-5 minutes on each side, or until they are golden brown and crispy on the outside. Once the lentil burgers are cooked through and have a nice crust, remove them from the skillet and let them rest on a plate lined with paper towels to absorb any excess oil. Assemble your lentil burgers on burger buns and add your desired toppings such as lettuce, tomato, onion, or condiments. Serve the lentil burgers while they are still warm and enjoy!", isLiked: true),
    
    Recipe(name: "Mushroom Risotto", ingredients: ["Arborio Rice", "Mushrooms", "Vegetable Broth", "Onion", "White Wine", "Olive Oil", "Parsley"], quantity: [200, 250, 500, 1, 100, 2, 1], preparation_time: "40 mins", type_dish: "First course", nutritional_values: "400 kcal", conservation: "Fridge", imageName: "risotto_funghi", description: "In a medium-sized saucepan, heat the vegetable broth over low heat. Keep it simmering throughout the cooking process. In a separate large saucepan or skillet, heat the olive oil and butter over medium heat. Add the chopped onion and minced garlic to the pan. Sauté for a few minutes until the onion becomes translucent and fragrant. Add the sliced mushrooms to the pan and cook until they have softened and released their moisture, about 5-7 minutes. Remove half of the cooked mushrooms from the pan and set them aside for later use. \n\nAdd the Arborio rice to the pan with the remaining mushrooms. Stir well to coat the rice with the oil and butter mixture. Pour in the white wine and stir continuously until it has been absorbed by the rice. Begin adding the simmering vegetable broth to the rice, one ladle at a time. Stir the rice frequently and allow each ladle of broth to be absorbed before adding the next one. \n\nContinue adding broth and stirring until the rice is al dente, which usually takes about 18-20 minutes. The rice should be creamy but still have a slight bite to it. Stir in the reserved cooked mushrooms and grated Parmesan cheese. Season with salt and pepper to taste. Remove the pan from heat and let the risotto rest for a minute or two. Serve the mushroom risotto hot, garnished with fresh chopped parsley.", isLiked: true),
    
    Recipe(name: "Chickpea Salad", ingredients: ["Canned Chickpeas", "Cherry Tomatoes", "Cucumbers", "Bell Peppers", "Onion", "Parsley", "Lemon"], quantity: [400, 10, 1, 1, 1, 2, 2, 1], preparation_time: "15 mins", type_dish: "Appetizer", nutritional_values: "300 kcal", conservation: "Fridge", imageName: "insalata_ceci", description: "In a large mixing bowl, combine the cooked chickpeas, diced cucumber, diced red bell pepper, finely chopped red onion, cherry tomatoes, sliced olives, and chopped fresh parsley. In a small bowl, whisk together the lemon juice, extra-virgin olive oil, salt, and pepper to create the dressing. \n\nPour the dressing over the chickpea mixture and toss well to coat all the ingredients evenly. Taste and adjust the seasoning if needed, adding more salt, pepper, or lemon juice according to your preference. Let the chickpea salad sit for at least 15 minutes to allow the flavors to meld together. \n\nServe the chickpea salad as a refreshing and nutritious side dish or as a light lunch option. You can garnish the salad with additional fresh herbs, such as mint or basil, for added freshness. Leftovers can be stored in an airtight container in the refrigerator for up to 3 days.",  isLiked: false),
    
    Recipe(name: "Whole Wheat Bread", ingredients: ["Whole Wheat Flour", "Brewer's Yeast"], quantity: [500, 300, 10, 10], preparation_time: "2h", type_dish: "Side dish", nutritional_values: "200 kcal", conservation: "Bakery", imageName: "pane_integrale", description:"In a small bowl, combine the warm water and honey (or maple syrup). Sprinkle the yeast over the mixture and let it sit for about 5 minutes, or until it becomes frothy. In a large mixing bowl, combine the whole wheat flour and salt. Make a well in the center of the flour mixture. \n\nPour the yeast mixture and olive oil into the well in the flour. Using a wooden spoon or your hands, gradually mix the flour into the liquid until a sticky dough forms. Turn the dough out onto a lightly floured surface and knead it for about 10 minutes, or until it becomes smooth and elastic. Add more flour if necessary to prevent sticking, but be careful not to add too much. \n\nShape the dough into a ball and place it back into the mixing bowl. Cover the bowl with a clean kitchen towel and let the dough rise in a warm, draft-free place for about 1 hour, or until it has doubled in size. Once the dough has risen, gently punch it down to release the air. \n\nTurn it out onto a floured surface and knead it for a minute or two to remove any remaining air bubbles. Shape the dough into a loaf by rolling it tightly from one end to the other. Place the loaf into a greased or parchment-lined bread pan. \n\nCover the bread pan with the kitchen towel and let the dough rise for another 30-45 minutes, or until it has risen just above the rim of the pan. Meanwhile, preheat the oven to 190°C (375°F). Once the dough has risen again, bake it in the preheated oven for 30-35 minutes, or until the crust is golden brown and the bread sounds hollow when tapped on the bottom. Remove the bread from the oven and let it cool in the pan for a few minutes. Then transfer it to a wire rack to cool completely before slicing.", isLiked: false)
    
    ]

    
}

var sharedRecipe = RecipeData()
